'use client'

import { useState } from 'react'
import { ArrowDown, ArrowRight, CalendarDays, Camera, Clock3, MapPin, Menu, Phone, Star, X } from 'lucide-react'

const services = [
  { name: 'Solo Corte', description: 'Corte de cabello adaptado a tu estilo.', duration: '35 min', price: 'Consultar', image: '/images/manicure-detail.png' },
  { name: 'Corte y Barba', description: 'Servicio completo de corte y arreglo de barba.', duration: '50 min', price: 'Consultar', image: '/images/hero-spa.png' },
  { name: 'Corte, Barba y Cejas', description: 'Experiencia total de barbería y perfilado.', duration: '60 min', price: 'Consultar', image: '/images/spa-detail.png' },
]

const treatments = [
  { eyebrow: '01 / BARBERÍA', title: 'Solo Corte', copy: 'Técnica precisa y acabado impecable.', color: 'bg-[#e8d8d0]' },
  { eyebrow: '02 / BARBA', title: 'Corte y Barba', copy: 'Cuida tu imagen con el ritual completo.', color: 'bg-[#d8cfc4]' },
  { eyebrow: '03 / RITUAL', title: 'Corte, Barba y Cejas', copy: 'Un trato personalizado para un estilo perfecto.', color: 'bg-[#dedbd2]' },
]

const gallery = ['/images/hero-spa.png', '/images/manicure-detail.png', '/images/spa-detail.png', '/images/hero-spa.png']

function SectionIntro({ eyebrow, title, copy, light = false }: { eyebrow: string; title: string; copy: string; light?: boolean }) {
  return <div className={`max-w-2xl ${light ? 'text-white' : ''}`}><p className="mb-4 text-[11px] font-semibold uppercase tracking-[0.24em] text-[#b86f54]">{eyebrow}</p><h2 className="font-serif text-4xl leading-[1.05] tracking-[-0.03em] md:text-6xl">{title}</h2><p className={`mt-6 max-w-lg text-base leading-7 ${light ? 'text-white/70' : 'text-zinc-500'}`}>{copy}</p></div>
}

function Header({ onMenu }: { onMenu: () => void }) {
  return <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="/" className="font-serif text-2xl tracking-[-0.04em] text-white">+58 BarberStudio<span className="text-[#d59a83]">.</span></a><nav className="hidden items-center gap-8 text-[11px] font-medium uppercase tracking-[0.18em] text-white/80 md:flex"><a href="#servicios" className="transition-colors hover:text-white">Servicios</a><a href="/gestionar" className="transition-colors hover:text-white">Gestionar Cita</a><a href="#equipo" className="transition-colors hover:text-white">Equipo</a><a href="#contacto" className="transition-colors hover:text-white">Contacto</a><a href="/login" className="transition-colors hover:text-white">Admin</a></nav><div className="flex items-center gap-3"><a href="/reservar" className="hidden border border-white/50 px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-white transition hover:bg-white hover:text-zinc-900 sm:block">Reservar cita</a><button aria-label="Abrir menú" onClick={onMenu} className="flex size-11 items-center justify-center border border-white/40 text-white md:hidden"><Menu /></button></div></div></header>
}

function Hero() {
  return <section id="inicio" className="relative flex min-h-[720px] items-end overflow-hidden bg-[#5d4a42] pb-16 md:min-h-[800px] md:pb-24"><img src="/images/hero-spa.png" alt="Barbería +58 Studio" className="absolute inset-0 size-full object-cover object-center opacity-80"/><div className="absolute inset-0 bg-gradient-to-r from-black/65 via-black/20 to-black/15"/><div className="relative mx-auto w-full max-w-7xl px-6 lg:px-10"><div className="max-w-3xl text-white"><p className="mb-6 text-[11px] font-semibold uppercase tracking-[0.3em] text-[#e7b4a1]">BarberStudio · Tenerife</p><h1 className="font-serif text-6xl leading-[0.93] tracking-[-0.055em] md:text-8xl">Tu estilo.<br/><em className="font-normal text-[#e7b4a1]">Tu sello.</em><br/>Tu espacio.</h1><p className="mt-8 max-w-md text-base leading-7 text-white/80">Descubre la experiencia de barbería diseñada para que te veas y te sientas impecable.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="/reservar" className="group inline-flex items-center gap-5 bg-[#c57d62] px-6 py-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-white transition hover:bg-[#ae684f]">Reservar mi cita <ArrowRight className="transition-transform group-hover:translate-x-1" /></a><a href="#servicios" className="inline-flex items-center gap-3 px-3 py-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-white/90 transition hover:text-white">Descubrir servicios <ArrowDown /></a></div></div><div className="mt-20 flex items-center gap-3 text-[10px] uppercase tracking-[0.2em] text-white/60"><span className="size-2 rounded-full bg-[#e7b4a1]"/> Tu cita empieza aquí</div></div></section>
}

function Services() { return <section id="servicios" className="bg-[#faf8f6] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Nuestros servicios" title="Barbería con estilo." copy="Cada servicio está pensado para ofrecerte precisión, estilo y un trato personalizado."/><div className="mt-16 grid gap-6 md:grid-cols-3">{services.map((service) => <article key={service.name} className="group"><div className="relative aspect-[0.82] overflow-hidden bg-[#e8e1dc]"><img src={service.image} alt={service.name} className="size-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute right-4 top-4 bg-white/90 px-3 py-2 text-xs font-medium">{service.price}</span></div><div className="flex items-start justify-between border-b border-zinc-200 py-5"><div><h3 className="font-serif text-2xl">{service.name}</h3><p className="mt-2 text-sm text-zinc-500">{service.description}</p><p className="mt-4 flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] text-zinc-400"><Clock3 /> {service.duration}</p></div><a href="/reservar"><ArrowRight className="mt-2 text-[#b86f54] transition-transform group-hover:translate-x-1"/></a></div></article>)}</div></div></section> }

function Treatments() { return <section className="bg-[#e8ddd6] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-10 md:flex-row md:items-end"><SectionIntro eyebrow="+58 BarberStudio" title="Cortes y arreglos de precisión." copy="Servicios esenciales para tu imagen diaria."/><a href="/reservar" className="inline-flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9f5e48]">Ver disponibilidad <ArrowRight /></a></div><div className="mt-16 grid gap-4 md:grid-cols-3">{treatments.map((item, index) => <article key={item.title} className={`${item.color} min-h-[330px] p-7 transition duration-500 hover:-translate-y-1 md:min-h-[420px] ${index === 1 ? 'md:mt-12' : ''}`}><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9f5e48]">{item.eyebrow}</p><div className="flex h-full flex-col justify-end"><h3 className="font-serif text-4xl leading-none tracking-[-0.04em]">{item.title}</h3><p className="mt-4 max-w-xs text-sm leading-6 text-zinc-600">{item.copy}</p></div></article>)}</div></div></section> }

function Experience() { return <section id="experiencia" className="bg-[#38312d] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-[0.8fr_1.2fr] md:items-center"><div><SectionIntro light eyebrow="La experiencia +58" title="Atención dedicada para ti." copy="Un espacio moderno en Santa Cruz de Tenerife para renovar tu corte y cuidar tu barba con la mejor atención."/><div className="mt-10 flex items-center gap-10"><div><p className="font-serif text-4xl">4.9</p><div className="mt-2 flex text-[#d59a83]"><Star fill="currentColor"/><Star fill="currentColor"/><Star fill="currentColor"/><Star fill="currentColor"/><Star fill="currentColor"/></div></div><div className="h-12 w-px bg-white/20"/><p className="max-w-[160px] text-sm leading-6 text-white/60">Clientes satisfechos que vuelven cada semana.</p></div></div><div className="relative aspect-[1.1] overflow-hidden"><img src="/images/manicure-detail.png" alt="BarberStudio +58" className="size-full object-cover"/><div className="absolute bottom-5 left-5 bg-[#faf8f6] px-5 py-4 text-zinc-900"><p className="font-serif text-xl">“Tu barbería de confianza.”</p><p className="mt-1 text-[10px] uppercase tracking-[0.16em] text-zinc-500">— Heber, Barber Studio</p></div></div></div></section> }

function Gallery() { return <section className="bg-[#faf8f6] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><SectionIntro eyebrow="Dentro del estudio" title="Un vistazo a nuestro espacio." copy="Detalles y cortes realizados en +58 BarberStudio."/><a href="#contacto" aria-label="Instagram" className="hidden size-12 items-center justify-center rounded-full border border-zinc-300 text-zinc-700 transition hover:bg-zinc-900 hover:text-white md:flex"><Camera /></a></div><div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((image, index) => <img key={`${image}-${index}`} src={image} alt={`Detalle +58 BarberStudio ${index + 1}`} className={`aspect-square w-full object-cover ${index === 1 ? 'md:mt-12' : ''} ${index === 2 ? 'md:-mt-8' : ''}`} />)}</div></div></section> }

function Team() { const people = [{ name: 'Heber', role: 'Barbero Principal & Fundador', initial: 'H' }]; return <section id="equipo" className="bg-[#f1ebe6] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Manos expertas" title="El equipo que te atiende." copy="Profesional dedicado a tu mejor versión."/><div className="mt-14 grid gap-5 sm:grid-cols-3">{people.map((person, index) => <article key={person.name} className="group"><div className={`flex aspect-[0.9] items-end p-6 ${['bg-[#c9b2a5]', 'bg-[#b7aaa0]', 'bg-[#d7c6ba]'][index]}`}><span className="font-serif text-[10rem] leading-none text-white/40 transition group-hover:text-white/60">{person.initial}</span></div><h3 className="mt-5 font-serif text-2xl">{person.name}</h3><p className="mt-1 text-sm text-zinc-500">{person.role}</p></article>)}</div></div></section> }

function BookingCTA() { return <section id="reserva" className="bg-[#c57d62] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.25em] text-white/70">Tu próxima cita</p><h2 className="max-w-xl font-serif text-5xl leading-[0.95] tracking-[-0.05em] md:text-7xl">Reserva tu hora<br/><em className="font-normal">ahora mismo.</em></h2></div><div className="max-w-sm"><p className="mb-7 text-base leading-7 text-white/80">Elige tu servicio, fecha y hora en tiempo real.</p><a href="/reservar" className="inline-flex items-center gap-4 bg-white px-6 py-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f5e48] transition hover:bg-[#f5e9e3]">Comenzar reserva <CalendarDays /></a></div></div></section> }

function Location() { return <section id="contacto" className="bg-[#faf8f6] px-6 py-24 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2 md:items-end"><SectionIntro eyebrow="Visítanos" title="+58 BarberStudio" copy="Santa Cruz de Tenerife · Islas Canarias"/><div className="flex flex-col gap-5 text-sm text-zinc-600"><p className="flex items-center gap-3"><MapPin className="text-[#b86f54]"/> Avenida de Los Majuelos 51C, 38008, Taco</p><p className="flex items-center gap-3"><Phone className="text-[#b86f54]"/> +34 664 345 827</p><p className="flex items-center gap-3"><Clock3 className="text-[#b86f54]"/> L–S 10:00–20:00</p><a href="/reservar" className="mt-3 inline-flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f5e48]">Reservar cita <ArrowRight /></a></div></div></section> }

function Footer() { return <footer className="bg-[#38312d] px-6 py-10 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><a href="/" className="font-serif text-3xl tracking-[-0.05em]">+58 BarberStudio<span className="text-[#d59a83]">.</span></a><p className="mt-2 text-xs text-white/45">Tu espacio de barbería en Tenerife.</p></div><div className="flex flex-wrap gap-6 text-[10px] uppercase tracking-[0.16em] text-white/55"><a href="/reservar" className="hover:text-white">Reservar</a><a href="/gestionar" className="hover:text-white">Gestionar Cita</a><a href="/login" className="hover:text-white">Acceso Admin</a></div><p className="text-xs text-white/35">© 2024 +58 BarberStudio</p></div></footer> }

export default function Page() { const [menuOpen, setMenuOpen] = useState(false); return <main><div className="relative"><Header onMenu={() => setMenuOpen(true)} /><Hero /></div><Services /><Treatments /><Experience /><Gallery /><Team /><BookingCTA /><Location /><Footer />{menuOpen && <div className="fixed inset-0 z-50 flex flex-col bg-[#38312d] p-6 text-white"><div className="flex items-center justify-between"><span className="font-serif text-2xl">+58 BarberStudio<span className="text-[#d59a83]">.</span></span><button aria-label="Cerrar menú" onClick={() => setMenuOpen(false)} className="flex size-11 items-center justify-center border border-white/30"><X /></button></div><nav className="mt-20 flex flex-col gap-7 font-serif text-4xl"><a href="/reservar" onClick={() => setMenuOpen(false)}>Reservar Cita</a><a href="/gestionar" onClick={() => setMenuOpen(false)}>Gestionar Cita</a><a href="#servicios" onClick={() => setMenuOpen(false)}>Servicios</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a><a href="/login" onClick={() => setMenuOpen(false)}>Admin</a></nav><div className="mt-auto border-t border-white/15 pt-6 text-sm text-white/55"><p>BarberStudio · Tenerife</p></div></div>}</main> }

export { ServiceCard, TreatmentCard, ProfessionalCard, ReviewCard, Gallery, BookingCTA, Location, Footer }

function ServiceCard() { return null }
function TreatmentCard() { return null }
function ProfessionalCard() { return null }
function ReviewCard() { return null }
